# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\configDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_configDialog(object):
    def setupUi(self, configDialog):
        configDialog.setObjectName("configDialog")
        configDialog.resize(400, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(configDialog.sizePolicy().hasHeightForWidth())
        configDialog.setSizePolicy(sizePolicy)
        configDialog.setMinimumSize(QtCore.QSize(400, 150))
        configDialog.setMaximumSize(QtCore.QSize(400, 150))
        configDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(configDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 80, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.amDir = QtWidgets.QLineEdit(configDialog)
        self.amDir.setGeometry(QtCore.QRect(160, 10, 191, 20))
        self.amDir.setObjectName("amDir")
        self.label = QtWidgets.QLabel(configDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label.setObjectName("label")
        self.amDirBtn = QtWidgets.QPushButton(configDialog)
        self.amDirBtn.setGeometry(QtCore.QRect(360, 10, 31, 21))
        self.amDirBtn.setObjectName("amDirBtn")
        self.label_2 = QtWidgets.QLabel(configDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.label_2.setObjectName("label_2")
        self.mameExe = QtWidgets.QLineEdit(configDialog)
        self.mameExe.setGeometry(QtCore.QRect(160, 40, 191, 20))
        self.mameExe.setObjectName("mameExe")
        self.mameExeBtn = QtWidgets.QPushButton(configDialog)
        self.mameExeBtn.setGeometry(QtCore.QRect(360, 40, 31, 21))
        self.mameExeBtn.setObjectName("mameExeBtn")
        self.label_3 = QtWidgets.QLabel(configDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 271, 16))
        self.label_3.setObjectName("label_3")
        self.okBtn = QtWidgets.QPushButton(configDialog)
        self.okBtn.setGeometry(QtCore.QRect(140, 120, 93, 28))
        self.okBtn.setObjectName("okBtn")

        self.retranslateUi(configDialog)
        self.buttonBox.accepted.connect(configDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(configDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(configDialog)

    def retranslateUi(self, configDialog):
        _translate = QtCore.QCoreApplication.translate
        configDialog.setWindowTitle(_translate("configDialog", "Configuration"))
        self.label.setText(_translate("configDialog", "AttractMode Directory"))
        self.amDirBtn.setText(_translate("configDialog", "..."))
        self.label_2.setText(_translate("configDialog", "Mame Executable"))
        self.mameExeBtn.setText(_translate("configDialog", "..."))
        self.label_3.setText(_translate("configDialog", "(Only necessary if you use a non-standard Mame build)"))
        self.okBtn.setText(_translate("configDialog", "OK"))
