# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AttractModeMameListMgr.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(768, 406)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(768, 406))
        Dialog.setMaximumSize(QtCore.QSize(768, 406))
        self.amDir = QtWidgets.QLineEdit(Dialog)
        self.amDir.setGeometry(QtCore.QRect(160, 10, 261, 20))
        self.amDir.setObjectName("amDir")
        self.amDirLbl = QtWidgets.QLabel(Dialog)
        self.amDirLbl.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.amDirLbl.setObjectName("amDirLbl")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 370, 671, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setGeometry(QtCore.QRect(20, 80, 731, 271))
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setColumnCount(4)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.headerItem().setText(1, "2")
        self.treeWidget.headerItem().setText(2, "3")
        self.treeWidget.headerItem().setText(3, "4")
        self.amDirBtn = QtWidgets.QPushButton(Dialog)
        self.amDirBtn.setGeometry(QtCore.QRect(430, 10, 21, 21))
        self.amDirBtn.setObjectName("amDirBtn")
        self.startBtn = QtWidgets.QPushButton(Dialog)
        self.startBtn.setGeometry(QtCore.QRect(700, 370, 51, 25))
        self.startBtn.setObjectName("startBtn")
        self.ptxt = QtWidgets.QLabel(Dialog)
        self.ptxt.setGeometry(QtCore.QRect(20, 370, 631, 21))
        self.ptxt.setAlignment(QtCore.Qt.AlignCenter)
        self.ptxt.setObjectName("ptxt")
        self.mameDir = QtWidgets.QLineEdit(Dialog)
        self.mameDir.setGeometry(QtCore.QRect(160, 40, 261, 20))
        self.mameDir.setObjectName("mameDir")
        self.mameDirLbl = QtWidgets.QLabel(Dialog)
        self.mameDirLbl.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.mameDirLbl.setObjectName("mameDirLbl")
        self.mameDirBtn = QtWidgets.QPushButton(Dialog)
        self.mameDirBtn.setGeometry(QtCore.QRect(430, 40, 21, 21))
        self.mameDirBtn.setObjectName("mameDirBtn")
        self.loadListBtn = QtWidgets.QPushButton(Dialog)
        self.loadListBtn.setGeometry(QtCore.QRect(470, 10, 93, 21))
        self.loadListBtn.setObjectName("loadListBtn")
        self.saveConfigBtn = QtWidgets.QPushButton(Dialog)
        self.saveConfigBtn.setGeometry(QtCore.QRect(570, 10, 93, 21))
        self.saveConfigBtn.setObjectName("saveConfigBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.amDirLbl.setText(_translate("Dialog", "AttractMode Directory"))
        self.amDirBtn.setText(_translate("Dialog", "..."))
        self.startBtn.setText(_translate("Dialog", "Start"))
        self.ptxt.setText(_translate("Dialog", "TextLabel"))
        self.mameDirLbl.setText(_translate("Dialog", "Mame Executable"))
        self.mameDirBtn.setText(_translate("Dialog", "..."))
        self.loadListBtn.setText(_translate("Dialog", "Load Mame.txt"))
        self.saveConfigBtn.setText(_translate("Dialog", "Save Config"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
