# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_findDlg(object):
    def setupUi(self, findDlg):
        findDlg.setObjectName("findDlg")
        findDlg.resize(400, 135)
        findDlg.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(findDlg)
        self.buttonBox.setGeometry(QtCore.QRect(310, 100, 71, 30))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.findLine = QtWidgets.QLineEdit(findDlg)
        self.findLine.setGeometry(QtCore.QRect(50, 10, 241, 20))
        self.findLine.setObjectName("findLine")
        self.findLbl = QtWidgets.QLabel(findDlg)
        self.findLbl.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.findLbl.setObjectName("findLbl")
        self.findBtn = QtWidgets.QPushButton(findDlg)
        self.findBtn.setGeometry(QtCore.QRect(310, 10, 71, 30))
        self.findBtn.setObjectName("findBtn")
        self.cbxGroups = QtWidgets.QCheckBox(findDlg)
        self.cbxGroups.setGeometry(QtCore.QRect(50, 80, 74, 17))
        self.cbxGroups.setObjectName("cbxGroups")
        self.cbxChildren = QtWidgets.QCheckBox(findDlg)
        self.cbxChildren.setGeometry(QtCore.QRect(50, 100, 74, 17))
        self.cbxChildren.setObjectName("cbxChildren")
        self.cbxInclSiblings = QtWidgets.QCheckBox(findDlg)
        self.cbxInclSiblings.setGeometry(QtCore.QRect(150, 40, 141, 17))
        self.cbxInclSiblings.setObjectName("cbxInclSiblings")
        self.cbxExactMatch = QtWidgets.QCheckBox(findDlg)
        self.cbxExactMatch.setGeometry(QtCore.QRect(50, 40, 91, 17))
        self.cbxExactMatch.setObjectName("cbxExactMatch")
        self.DuplicatesBtn = QtWidgets.QPushButton(findDlg)
        self.DuplicatesBtn.setGeometry(QtCore.QRect(310, 50, 71, 28))
        self.DuplicatesBtn.setObjectName("DuplicatesBtn")

        self.retranslateUi(findDlg)
        self.buttonBox.accepted.connect(findDlg.accept)
        self.buttonBox.rejected.connect(findDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(findDlg)

    def retranslateUi(self, findDlg):
        _translate = QtCore.QCoreApplication.translate
        findDlg.setWindowTitle(_translate("findDlg", "Find"))
        self.findLbl.setText(_translate("findDlg", "Find"))
        self.findBtn.setText(_translate("findDlg", "Search"))
        self.cbxGroups.setText(_translate("findDlg", "Groups"))
        self.cbxChildren.setText(_translate("findDlg", "Children"))
        self.cbxInclSiblings.setText(_translate("findDlg", "Include siblings in results"))
        self.cbxExactMatch.setText(_translate("findDlg", "Exact Match"))
        self.DuplicatesBtn.setText(_translate("findDlg", "Duplicates"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    findDlg = QtWidgets.QDialog()
    ui = Ui_findDlg()
    ui.setupUi(findDlg)
    findDlg.show()
    sys.exit(app.exec_())
